export const SUCCESS_MSG = 'SUCCESS'
export const ERR_MSG = 'ERR'
export const BLANK_MSG = 'Field can not be blank'
export const EXIST_MSG = 'Value is Exist'
export const DATE_MSG = 'Start date and end date are incorrectly formatted'
